-- =====================================================================
-- KHỐI 4.5 — TRIGGER LẶP LẠI: updated_at/version + AUDIT
-- (Sinh từ danh mục hệ thống; mỗi bảng một dòng tường minh. Gắn sau cùng để mọi hàm đã tồn tại.)
-- =====================================================================

-- 4.5.100  Cập nhật updated_at + tăng version (khóa lạc quan) — bảng có cả hai cột
CREATE TRIGGER trg_academic_records__touch BEFORE UPDATE ON academic_records FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_albums__touch BEFORE UPDATE ON albums FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_announcements__touch BEFORE UPDATE ON announcements FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_assets__touch BEFORE UPDATE ON assets FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_attendance_records__touch BEFORE UPDATE ON attendance_records FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_categories__touch BEFORE UPDATE ON categories FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_catholic_profiles__touch BEFORE UPDATE ON catholic_profiles FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_cleaning_areas__touch BEFORE UPDATE ON cleaning_areas FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_contribution_plans__touch BEFORE UPDATE ON contribution_plans FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_contributions__touch BEFORE UPDATE ON contributions FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_duty_assignments__touch BEFORE UPDATE ON duty_assignments FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_duty_rosters__touch BEFORE UPDATE ON duty_rosters FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_event_recurrence_rules__touch BEFORE UPDATE ON event_recurrence_rules FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_events__touch BEFORE UPDATE ON events FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_expense_vouchers__touch BEFORE UPDATE ON expense_vouchers FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_financial_periods__touch BEFORE UPDATE ON financial_periods FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_floors__touch BEFORE UPDATE ON floors FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_forum_posts__touch BEFORE UPDATE ON forum_posts FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_funds__touch BEFORE UPDATE ON funds FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_grade_scales__touch BEFORE UPDATE ON grade_scales FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_leave_requests__touch BEFORE UPDATE ON leave_requests FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_maintenance_issues__touch BEFORE UPDATE ON maintenance_issues FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_member_private_details__touch BEFORE UPDATE ON member_private_details FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_members__touch BEFORE UPDATE ON members FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_polls__touch BEFORE UPDATE ON polls FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_rooms__touch BEFORE UPDATE ON rooms FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_settings__touch BEFORE UPDATE ON settings FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_student_profiles__touch BEFORE UPDATE ON student_profiles FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();
CREATE TRIGGER trg_users__touch BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION app.tg_touch_versioned();

-- 4.5.101  Chỉ cập nhật updated_at — bảng không có cột version
CREATE TRIGGER trg_academic_years__touch BEFORE UPDATE ON academic_years FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_ai_budgets__touch BEFORE UPDATE ON ai_budgets FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_board_terms__touch BEFORE UPDATE ON board_terms FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_data_subject_requests__touch BEFORE UPDATE ON data_subject_requests FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_duty_swap_requests__touch BEFORE UPDATE ON duty_swap_requests FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_forum_comments__touch BEFORE UPDATE ON forum_comments FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_grade_records__touch BEFORE UPDATE ON grade_records FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_laundry_bookings__touch BEFORE UPDATE ON laundry_bookings FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_laundry_machines__touch BEFORE UPDATE ON laundry_machines FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_liturgy_assignments__touch BEFORE UPDATE ON liturgy_assignments FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_meal_menus__touch BEFORE UPDATE ON meal_menus FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_member_applications__touch BEFORE UPDATE ON member_applications FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_member_guardians__touch BEFORE UPDATE ON member_guardians FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_notification_preferences__touch BEFORE UPDATE ON notification_preferences FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_pantry_items__touch BEFORE UPDATE ON pantry_items FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_prayer_intentions__touch BEFORE UPDATE ON prayer_intentions FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_reflections__touch BEFORE UPDATE ON reflections FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_room_assignments__touch BEFORE UPDATE ON room_assignments FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_storage_files__touch BEFORE UPDATE ON storage_files FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_study_goals__touch BEFORE UPDATE ON study_goals FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_tutoring_matches__touch BEFORE UPDATE ON tutoring_matches FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_tutoring_offers__touch BEFORE UPDATE ON tutoring_offers FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_tutoring_requests__touch BEFORE UPDATE ON tutoring_requests FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_universities__touch BEFORE UPDATE ON universities FOR EACH ROW EXECUTE FUNCTION app.tg_touch();
CREATE TRIGGER trg_vendors__touch BEFORE UPDATE ON vendors FOR EACH ROW EXECUTE FUNCTION app.tg_touch();

-- 4.5.102  Audit: bảng tài chính, phân quyền, hồ sơ nhạy cảm, phân phòng, điểm số, trực nhật, cấu hình
--          (cột khóa, cột bị che). poll_votes và prayer_intention_authors cố ý KHÔNG audit để giữ ẩn danh.
CREATE TRIGGER trg_users__audit AFTER INSERT OR UPDATE OR DELETE ON users FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id', 'password_hash');
CREATE TRIGGER trg_user_roles__audit AFTER INSERT OR UPDATE OR DELETE ON user_roles FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_role_delegations__audit AFTER INSERT OR UPDATE OR DELETE ON role_delegations FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_roles__audit AFTER INSERT OR UPDATE OR DELETE ON roles FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_role_permissions__audit AFTER INSERT OR UPDATE OR DELETE ON role_permissions FOR EACH ROW EXECUTE FUNCTION app.tg_audit('role_id,permission_code');
CREATE TRIGGER trg_settings__audit AFTER INSERT OR UPDATE OR DELETE ON settings FOR EACH ROW EXECUTE FUNCTION app.tg_audit('key');
CREATE TRIGGER trg_categories__audit AFTER INSERT OR UPDATE OR DELETE ON categories FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_user_mfa_factors__audit AFTER INSERT OR UPDATE OR DELETE ON user_mfa_factors FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id', 'secret_enc');
CREATE TRIGGER trg_members__audit AFTER INSERT OR UPDATE OR DELETE ON members FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id', 'contact_phone_e164,contact_email');
CREATE TRIGGER trg_member_private_details__audit AFTER INSERT OR UPDATE OR DELETE ON member_private_details FOR EACH ROW EXECUTE FUNCTION app.tg_audit('member_id', 'national_id_enc,national_id_bidx,national_id_last4,birth_date,hometown,home_address');
CREATE TRIGGER trg_member_guardians__audit AFTER INSERT OR UPDATE OR DELETE ON member_guardians FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id', 'full_name,phone_enc,phone_last4');
CREATE TRIGGER trg_catholic_profiles__audit AFTER INSERT OR UPDATE OR DELETE ON catholic_profiles FOR EACH ROW EXECUTE FUNCTION app.tg_audit('member_id', 'holy_name,parish_name,pastor_name');
CREATE TRIGGER trg_member_sacraments__audit AFTER INSERT OR UPDATE OR DELETE ON member_sacraments FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id', 'place');
CREATE TRIGGER trg_student_profiles__audit AFTER INSERT OR UPDATE OR DELETE ON student_profiles FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id', 'student_code,major');
CREATE TRIGGER trg_consents__audit AFTER INSERT OR UPDATE OR DELETE ON consents FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id', 'ip,user_agent');
CREATE TRIGGER trg_data_subject_requests__audit AFTER INSERT OR UPDATE OR DELETE ON data_subject_requests FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id', 'details,resolution_note');
CREATE TRIGGER trg_board_terms__audit AFTER INSERT OR UPDATE OR DELETE ON board_terms FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_member_positions__audit AFTER INSERT OR UPDATE OR DELETE ON member_positions FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_academic_years__audit AFTER INSERT OR UPDATE OR DELETE ON academic_years FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_semesters__audit AFTER INSERT OR UPDATE OR DELETE ON semesters FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_member_applications__audit AFTER INSERT OR UPDATE OR DELETE ON member_applications FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_floors__audit AFTER INSERT OR UPDATE OR DELETE ON floors FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_rooms__audit AFTER INSERT OR UPDATE OR DELETE ON rooms FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_room_assignments__audit AFTER INSERT OR UPDATE OR DELETE ON room_assignments FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_funds__audit AFTER INSERT OR UPDATE OR DELETE ON funds FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_financial_periods__audit AFTER INSERT OR UPDATE OR DELETE ON financial_periods FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_period_fund_balances__audit AFTER INSERT OR UPDATE OR DELETE ON period_fund_balances FOR EACH ROW EXECUTE FUNCTION app.tg_audit('period_id,fund_id');
CREATE TRIGGER trg_expense_vouchers__audit AFTER INSERT OR UPDATE OR DELETE ON expense_vouchers FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_expense_approvals__audit AFTER INSERT OR UPDATE OR DELETE ON expense_approvals FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_contribution_plans__audit AFTER INSERT OR UPDATE OR DELETE ON contribution_plans FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_contributions__audit AFTER INSERT OR UPDATE OR DELETE ON contributions FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_contribution_payments__audit AFTER INSERT OR UPDATE OR DELETE ON contribution_payments FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_contribution_payment_allocations__audit AFTER INSERT OR UPDATE OR DELETE ON contribution_payment_allocations FOR EACH ROW EXECUTE FUNCTION app.tg_audit('payment_id,contribution_id');
CREATE TRIGGER trg_bank_statement_lines__audit AFTER INSERT OR UPDATE OR DELETE ON bank_statement_lines FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_period_reconciliations__audit AFTER INSERT OR UPDATE OR DELETE ON period_reconciliations FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_duty_rosters__audit AFTER INSERT OR UPDATE OR DELETE ON duty_rosters FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_duty_assignments__audit AFTER INSERT OR UPDATE OR DELETE ON duty_assignments FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_duty_assignment_members__audit AFTER INSERT OR UPDATE OR DELETE ON duty_assignment_members FOR EACH ROW EXECUTE FUNCTION app.tg_audit('assignment_id,member_id');
CREATE TRIGGER trg_duty_reviews__audit AFTER INSERT OR UPDATE OR DELETE ON duty_reviews FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_duty_review_appeals__audit AFTER INSERT OR UPDATE OR DELETE ON duty_review_appeals FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_duty_swap_requests__audit AFTER INSERT OR UPDATE OR DELETE ON duty_swap_requests FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_cleaning_areas__audit AFTER INSERT OR UPDATE OR DELETE ON cleaning_areas FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_duty_shifts__audit AFTER INSERT OR UPDATE OR DELETE ON duty_shifts FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_merit_rules__audit AFTER INSERT OR UPDATE OR DELETE ON merit_rules FOR EACH ROW EXECUTE FUNCTION app.tg_audit('code');
CREATE TRIGGER trg_academic_records__audit AFTER INSERT OR UPDATE OR DELETE ON academic_records FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_grade_records__audit AFTER INSERT OR UPDATE OR DELETE ON grade_records FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_grade_scales__audit AFTER INSERT OR UPDATE OR DELETE ON grade_scales FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_grade_scale_bands__audit AFTER INSERT OR UPDATE OR DELETE ON grade_scale_bands FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_grade_rank_bands__audit AFTER INSERT OR UPDATE OR DELETE ON grade_rank_bands FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_tutoring_matches__audit AFTER INSERT OR UPDATE OR DELETE ON tutoring_matches FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_events__audit AFTER INSERT OR UPDATE OR DELETE ON events FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_leave_requests__audit AFTER INSERT OR UPDATE OR DELETE ON leave_requests FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id', 'reason,destination,contact_phone_e164');
CREATE TRIGGER trg_polls__audit AFTER INSERT OR UPDATE OR DELETE ON polls FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_attendance_records__audit AFTER INSERT OR UPDATE OR DELETE ON attendance_records FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_assets__audit AFTER INSERT OR UPDATE OR DELETE ON assets FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_maintenance_issues__audit AFTER INSERT OR UPDATE OR DELETE ON maintenance_issues FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_repair_costs__audit AFTER INSERT OR UPDATE OR DELETE ON repair_costs FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_asset_loans__audit AFTER INSERT OR UPDATE OR DELETE ON asset_loans FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_announcements__audit AFTER INSERT OR UPDATE OR DELETE ON announcements FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_policy_documents__audit AFTER INSERT OR UPDATE OR DELETE ON policy_documents FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_content_reports__audit AFTER INSERT OR UPDATE OR DELETE ON content_reports FOR EACH ROW EXECUTE FUNCTION app.tg_audit('id');
CREATE TRIGGER trg_album_member_tags__audit AFTER INSERT OR UPDATE OR DELETE ON album_member_tags FOR EACH ROW EXECUTE FUNCTION app.tg_audit('album_id,member_id');
CREATE TRIGGER trg_ai_task_types__audit AFTER INSERT OR UPDATE OR DELETE ON ai_task_types FOR EACH ROW EXECUTE FUNCTION app.tg_audit('code');
CREATE TRIGGER trg_ai_budgets__audit AFTER INSERT OR UPDATE OR DELETE ON ai_budgets FOR EACH ROW EXECUTE FUNCTION app.tg_audit('month');
