-- =====================================================================
-- KHỐI 4.7.1 — SEED RBAC: vai trò, quyền, ma trận vai trò × quyền
-- (nguồn chuẩn của ma trận quyền ở Phần 4.6 và đặc tả API Phần 6)
-- =====================================================================

INSERT INTO roles (code, name_vi, rank, description, is_system) VALUES
  ('admin', 'Admin (quản trị kỹ thuật)', 10, 'Quản trị hạ tầng/tài khoản/cấu hình kỹ thuật. KHÔNG duyệt chi, KHÔNG xem dữ liệu nhạy cảm của thành viên.', true),
  ('house_head', 'Trưởng nhà', 20, 'Đại diện pháp nhân, nhân sự, duyệt đơn, đồng ký xuất quỹ, xác nhận chốt sổ, quyết định khiếu nại.', true),
  ('vice_head', 'Phó nhà', 30, 'Hỗ trợ quản lý: điểm danh, phân công, lịch sự kiện, nghiệm thu trực nhật, xử lý sự cố (có thể giới hạn theo tầng/khu vực).', true),
  ('treasurer', 'Thủ quỹ', 30, 'Sổ quỹ, thu/chi, đối soát chứng từ, ma trận đóng quỹ, đề nghị chốt sổ.', true),
  ('liturgy_lead', 'Trưởng ban Phụng vụ', 40, '[ĐỀ XUẤT] Quản lý lịch phụng vụ, phân công đọc sách thánh/giúp lễ/hát, điểm danh buổi phụng vụ.', true),
  ('kitchen_lead', 'Trưởng ban Ẩm thực', 40, '[ĐỀ XUẤT] Quản lý thực đơn, chốt suất ăn, phân công đi chợ/trực bếp.', true),
  ('media_lead', 'Trưởng ban Truyền thông', 40, '[ĐỀ XUẤT] Kiểm duyệt album/khoảnh khắc, đăng bản tin.', true),
  ('member', 'Thành viên', 90, 'Vai trò nền của mọi thành viên: xem hồ sơ của mình, check-in, nhập điểm, báo hỏng, bỏ phiếu, đặt lịch giặt.', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO permissions (code, module, description, is_sensitive) VALUES
  ('auth.user.read', 'auth', 'Xem danh sách tài khoản', false),
  ('auth.user.manage', 'auth', 'Mời/tạo/khóa/mở khóa tài khoản, đặt lại mật khẩu', false),
  ('auth.role.assign', 'auth', 'Gán/thu hồi vai trò và phạm vi', true),
  ('auth.role.delegate', 'auth', 'Tạo ủy quyền tạm thời cho vai trò mình đang giữ', false),
  ('auth.session.revoke_any', 'auth', 'Thu hồi phiên đăng nhập của người khác', false),
  ('audit.log.read', 'audit', 'Xem nhật ký kiểm toán chung', true),
  ('audit.finance.read', 'audit', 'Xem nhật ký kiểm toán tài chính', true),
  ('audit.sensitive.read', 'audit', 'Xem nhật ký kiểm toán của dữ liệu cá nhân nhạy cảm (hồ sơ tầng 2–3, điểm số, đồng ý, yêu cầu của chủ thể dữ liệu) — Admin kỹ thuật KHÔNG có', true),
  ('setting.read', 'setting', 'Đọc cấu hình hệ thống', false),
  ('setting.write', 'setting', 'Sửa cấu hình hệ thống', false),
  ('category.manage', 'setting', 'Quản lý danh mục (chi phí, sự kiện, thông báo…)', false),
  ('term.manage', 'setting', 'Quản lý năm học, học kỳ, nhiệm kỳ', false),
  ('term.handover', 'setting', 'Đóng nhiệm kỳ và bàn giao chức vụ', false),
  ('member.read', 'member', 'Xem danh bạ cộng đoàn (tầng 1)', false),
  ('member.create', 'member', 'Thêm hồ sơ thành viên', false),
  ('member.update', 'member', 'Sửa hồ sơ tầng 1 (tên, trách vụ, trạng thái liên lạc)', false),
  ('member.status.change', 'member', 'Chuyển trạng thái cư trú (tạm vắng, cựu, rời)', false),
  ('member.private.read', 'member', 'Xem dữ liệu tầng 2: ngày sinh, quê quán, địa chỉ', true),
  ('member.private.write', 'member', 'Sửa dữ liệu tầng 2', true),
  ('member.guardian.read', 'member', 'Xem người liên lạc khẩn cấp / giám hộ', true),
  ('member.national_id.read', 'member', 'Giải mã và xem số CCCD (mỗi lần xem ghi nhật ký)', true),
  ('catholic.read_all', 'member', 'Xem hồ sơ Công giáo của người khác (chỉ khi người đó đã đồng ý)', true),
  ('consent.read_all', 'member', 'Xem tình trạng đồng ý của mọi thành viên', false),
  ('dsr.manage', 'member', 'Xử lý yêu cầu quyền của chủ thể dữ liệu', true),
  ('application.review', 'member', 'Duyệt đơn xin vào lưu xá / tài khoản chờ phê duyệt', false),
  ('position.manage', 'member', 'Gán trách vụ theo nhiệm kỳ', false),
  ('house.read', 'house', 'Xem sơ đồ nhà, phòng, tình trạng phòng', false),
  ('house.structure.manage', 'house', 'Tạo/sửa/xóa tầng, phòng, tiện ích, bố cục', false),
  ('house.assign', 'house', 'Xếp/chuyển/hủy phân phòng', false),
  ('asset.read', 'house', 'Xem sổ tài sản/thiết bị', false),
  ('asset.manage', 'house', 'Quản lý tài sản, thiết bị, lịch bảo trì định kỳ', false),
  ('duty.read', 'duty', 'Xem lịch trực và kết quả', false),
  ('duty.manage', 'duty', 'Lập roster, phân công, điều chỉnh người trực', false),
  ('duty.area.manage', 'duty', 'Quản lý khu vực vệ sinh, ca trực, checklist', false),
  ('duty.checkin', 'duty', 'Check-in ca trực của chính mình', false),
  ('duty.review', 'duty', 'Nghiệm thu ca trực (không được nghiệm thu ca của mình)', false),
  ('duty.swap.request', 'duty', 'Xin đổi ca', false),
  ('duty.swap.approve', 'duty', 'Duyệt đổi ca', false),
  ('duty.appeal.decide', 'duty', 'Quyết định khiếu nại kết quả nghiệm thu', false),
  ('merit.read_all', 'duty', 'Xem điểm đóng góp của mọi thành viên', false),
  ('merit.adjust', 'duty', 'Cộng/trừ điểm đóng góp thủ công (có lý do)', false),
  ('academic.write_own', 'academic', 'Nhập/sửa bảng điểm của chính mình', false),
  ('academic.read_all', 'academic', 'Xem bảng điểm chi tiết của người khác (cần đồng ý)', true),
  ('academic.read_aggregate', 'academic', 'Xem thống kê học tập tổng hợp, ẩn danh', false),
  ('academic.verify', 'academic', 'Xác minh minh chứng bảng điểm', false),
  ('academic.scale.manage', 'academic', 'Quản lý trường đại học và thang điểm quy đổi', false),
  ('tutoring.participate', 'academic', 'Đăng ký kèm/xin kèm học', false),
  ('tutoring.manage', 'academic', 'Ghép cặp và theo dõi phụ đạo', false),
  ('event.read', 'event', 'Xem lịch sự kiện', false),
  ('event.manage', 'event', 'Tạo/sửa/hủy sự kiện, lịch định kỳ', false),
  ('event.attendance.record', 'event', 'Điểm danh thủ công, chỉnh sửa trạng thái điểm danh', false),
  ('event.attendance.read_all', 'event', 'Xem danh sách điểm danh đầy đủ', false),
  ('event.qr.manage', 'event', 'Mở/đóng phiên điểm danh QR', false),
  ('leave.request', 'event', 'Gửi đơn xin phép vắng/ra ngoài/về muộn', false),
  ('leave.review', 'event', 'Duyệt đơn xin phép', false),
  ('poll.manage', 'event', 'Tạo/đóng khảo sát và biểu quyết', false),
  ('poll.vote', 'event', 'Bỏ phiếu', false),
  ('liturgy.manage', 'event', 'Lập lịch và phân công phụng vụ', false),
  ('finance.summary.read', 'finance', 'Xem tổng quan quỹ cho thành viên (số dư, thu/chi theo danh mục)', false),
  ('finance.ledger.read', 'finance', 'Xem sổ cái chi tiết', false),
  ('finance.fund.manage', 'finance', 'Quản lý túi quỹ', false),
  ('finance.expense.create', 'finance', 'Tạo đề xuất/phiếu chi của chính mình', false),
  ('finance.expense.read_all', 'finance', 'Xem mọi phiếu chi', false),
  ('finance.expense.approve', 'finance', 'Phê duyệt/từ chối phiếu chi (không tự duyệt; trên ngưỡng cần 2 chữ ký; Phó nhà chỉ là chữ ký thứ hai)', true),
  ('finance.expense.pay', 'finance', 'Ghi nhận đã chi (sinh bút toán sổ cái)', true),
  ('finance.expense.reverse', 'finance', 'Đảo/hủy phiếu chi đã chi bằng bút toán đảo', true),
  ('finance.contribution.plan.manage', 'finance', 'Lập kế hoạch thu quỹ và sinh khoản phải thu', false),
  ('finance.contribution.record', 'finance', 'Ghi nhận khoản thu quỹ', true),
  ('finance.contribution.waive', 'finance', 'Miễn/giảm/gia hạn khoản phải thu', true),
  ('finance.contribution.read_all', 'finance', 'Xem ma trận đóng quỹ của mọi thành viên', false),
  ('finance.period.close', 'finance', 'Chốt sổ tháng (bước 1 — Thủ quỹ)', true),
  ('finance.period.confirm', 'finance', 'Xác nhận chốt sổ tháng (bước 2 — Trưởng nhà)', true),
  ('finance.period.reopen', 'finance', 'Mở lại kỳ đã chốt (bắt buộc lý do, ghi kiểm toán)', true),
  ('finance.reconcile', 'finance', 'Nhập sao kê ngân hàng và đối soát', true),
  ('finance.report.export', 'finance', 'Xuất báo cáo tài chính (PDF/Excel)', false),
  ('finance.ledger.adjust', 'finance', 'Ghi thủ công bút toán số dư đầu kỳ / điều chỉnh vào sổ cái (kèm lý do, ghi kiểm toán)', true),
  ('finance.settings.write', 'finance', 'Sửa cấu hình tài chính (mức quỹ, ngưỡng hai chữ ký, ngưỡng hóa đơn, bắt buộc đối soát) — Admin kỹ thuật KHÔNG có quyền này', true),
  ('issue.create', 'facility', 'Báo hỏng', false),
  ('issue.read', 'facility', 'Xem danh sách sự cố', false),
  ('issue.triage', 'facility', 'Phân loại, đặt mức khẩn, phân công xử lý', false),
  ('issue.resolve', 'facility', 'Cập nhật tiến độ và đóng sự cố', false),
  ('issue.cost.propose', 'facility', 'Đề xuất chi phí sửa chữa (tạo phiếu chi liên kết)', false),
  ('vendor.manage', 'facility', 'Quản lý danh bạ thợ/nhà cung cấp', false),
  ('announcement.read', 'community', 'Xem thông báo', false),
  ('announcement.create', 'community', 'Đăng thông báo', false),
  ('announcement.pin', 'community', 'Ghim/bỏ ghim, đặt thông báo cần xác nhận đã đọc', false),
  ('forum.post', 'community', 'Đăng bài, bình luận, thả tim diễn đàn', false),
  ('forum.moderate', 'community', 'Kiểm duyệt/ẩn/khóa bài diễn đàn', false),
  ('prayer.post', 'community', 'Gửi ý cầu nguyện, hiệp ý cầu nguyện', false),
  ('prayer.moderate', 'community', 'Ẩn ý cầu nguyện vi phạm', false),
  ('prayer.reveal_author', 'community', 'Xem tác giả ý cầu nguyện ẩn danh (chỉ khi có báo cáo vi phạm; ghi kiểm toán)', true),
  ('album.create', 'community', 'Tạo album và tải ảnh khoảnh khắc', false),
  ('album.moderate', 'community', 'Kiểm duyệt/xóa album, ảnh, thẻ tên', false),
  ('laundry.book', 'community', 'Đặt lịch giặt', false),
  ('laundry.manage', 'community', 'Quản lý máy giặt, hủy/điều chỉnh lịch', false),
  ('meal.register', 'community', 'Đăng ký suất ăn của mình', false),
  ('meal.manage', 'community', 'Quản lý thực đơn, chốt suất ăn, đăng ký hộ', false),
  ('policy.manage', 'community', 'Soạn/ban hành nội quy và tài liệu cần xác nhận', false),
  ('policy.acknowledge', 'community', 'Xác nhận đã đọc nội quy', false),
  ('notification.send', 'community', 'Gửi thông báo đến nhóm đối tượng', false),
  ('storage.upload', 'storage', 'Xin URL tải lên và tải tệp', false),
  ('ai.use', 'ai', 'Dùng tính năng AI hỗ trợ (hỏi đáp nội quy, gợi ý)', false),
  ('ai.review', 'ai', 'Duyệt/từ chối gợi ý AI trong phạm vi nghiệp vụ của mình', false),
  ('ai.manage', 'ai', 'Quản lý cấu hình, ngân sách và nhật ký AI', false)
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_code)
SELECT r.id, x.permission_code
  FROM (VALUES
    ('admin', 'auth.user.read'),
    ('house_head', 'auth.user.read'),
    ('admin', 'auth.user.manage'),
    ('house_head', 'auth.user.manage'),
    ('house_head', 'auth.role.assign'),
    ('house_head', 'auth.role.delegate'),
    ('vice_head', 'auth.role.delegate'),
    ('treasurer', 'auth.role.delegate'),
    ('admin', 'auth.session.revoke_any'),
    ('house_head', 'auth.session.revoke_any'),
    ('admin', 'audit.log.read'),
    ('house_head', 'audit.log.read'),
    ('house_head', 'audit.finance.read'),
    ('treasurer', 'audit.finance.read'),
    ('house_head', 'audit.sensitive.read'),
    ('admin', 'setting.read'),
    ('house_head', 'setting.read'),
    ('vice_head', 'setting.read'),
    ('treasurer', 'setting.read'),
    ('liturgy_lead', 'setting.read'),
    ('kitchen_lead', 'setting.read'),
    ('media_lead', 'setting.read'),
    ('member', 'setting.read'),
    ('admin', 'setting.write'),
    ('house_head', 'setting.write'),
    ('admin', 'category.manage'),
    ('house_head', 'category.manage'),
    ('vice_head', 'category.manage'),
    ('treasurer', 'category.manage'),
    ('house_head', 'term.manage'),
    ('house_head', 'term.handover'),
    ('admin', 'member.read'),
    ('house_head', 'member.read'),
    ('vice_head', 'member.read'),
    ('treasurer', 'member.read'),
    ('liturgy_lead', 'member.read'),
    ('kitchen_lead', 'member.read'),
    ('media_lead', 'member.read'),
    ('member', 'member.read'),
    ('house_head', 'member.create'),
    ('vice_head', 'member.create'),
    ('house_head', 'member.update'),
    ('vice_head', 'member.update'),
    ('house_head', 'member.status.change'),
    ('house_head', 'member.private.read'),
    ('vice_head', 'member.private.read'),
    ('house_head', 'member.private.write'),
    ('vice_head', 'member.private.write'),
    ('house_head', 'member.guardian.read'),
    ('vice_head', 'member.guardian.read'),
    ('house_head', 'member.national_id.read'),
    ('house_head', 'catholic.read_all'),
    ('vice_head', 'catholic.read_all'),
    ('liturgy_lead', 'catholic.read_all'),
    ('house_head', 'consent.read_all'),
    ('admin', 'dsr.manage'),
    ('house_head', 'dsr.manage'),
    ('house_head', 'application.review'),
    ('vice_head', 'application.review'),
    ('house_head', 'position.manage'),
    ('admin', 'house.read'),
    ('house_head', 'house.read'),
    ('vice_head', 'house.read'),
    ('treasurer', 'house.read'),
    ('liturgy_lead', 'house.read'),
    ('kitchen_lead', 'house.read'),
    ('media_lead', 'house.read'),
    ('member', 'house.read'),
    ('house_head', 'house.structure.manage'),
    ('vice_head', 'house.structure.manage'),
    ('house_head', 'house.assign'),
    ('vice_head', 'house.assign'),
    ('admin', 'asset.read'),
    ('house_head', 'asset.read'),
    ('vice_head', 'asset.read'),
    ('treasurer', 'asset.read'),
    ('liturgy_lead', 'asset.read'),
    ('kitchen_lead', 'asset.read'),
    ('media_lead', 'asset.read'),
    ('member', 'asset.read'),
    ('house_head', 'asset.manage'),
    ('vice_head', 'asset.manage'),
    ('admin', 'duty.read'),
    ('house_head', 'duty.read'),
    ('vice_head', 'duty.read'),
    ('treasurer', 'duty.read'),
    ('liturgy_lead', 'duty.read'),
    ('kitchen_lead', 'duty.read'),
    ('media_lead', 'duty.read'),
    ('member', 'duty.read'),
    ('house_head', 'duty.manage'),
    ('vice_head', 'duty.manage'),
    ('house_head', 'duty.area.manage'),
    ('vice_head', 'duty.area.manage'),
    ('member', 'duty.checkin'),
    ('house_head', 'duty.review'),
    ('vice_head', 'duty.review'),
    ('member', 'duty.swap.request'),
    ('house_head', 'duty.swap.approve'),
    ('vice_head', 'duty.swap.approve'),
    ('house_head', 'duty.appeal.decide'),
    ('house_head', 'merit.read_all'),
    ('vice_head', 'merit.read_all'),
    ('house_head', 'merit.adjust'),
    ('vice_head', 'merit.adjust'),
    ('member', 'academic.write_own'),
    ('house_head', 'academic.read_all'),
    ('vice_head', 'academic.read_all'),
    ('house_head', 'academic.read_aggregate'),
    ('vice_head', 'academic.read_aggregate'),
    ('house_head', 'academic.verify'),
    ('vice_head', 'academic.verify'),
    ('admin', 'academic.scale.manage'),
    ('house_head', 'academic.scale.manage'),
    ('member', 'tutoring.participate'),
    ('house_head', 'tutoring.manage'),
    ('vice_head', 'tutoring.manage'),
    ('admin', 'event.read'),
    ('house_head', 'event.read'),
    ('vice_head', 'event.read'),
    ('treasurer', 'event.read'),
    ('liturgy_lead', 'event.read'),
    ('kitchen_lead', 'event.read'),
    ('media_lead', 'event.read'),
    ('member', 'event.read'),
    ('house_head', 'event.manage'),
    ('vice_head', 'event.manage'),
    ('liturgy_lead', 'event.manage'),
    ('house_head', 'event.attendance.record'),
    ('vice_head', 'event.attendance.record'),
    ('liturgy_lead', 'event.attendance.record'),
    ('house_head', 'event.attendance.read_all'),
    ('vice_head', 'event.attendance.read_all'),
    ('liturgy_lead', 'event.attendance.read_all'),
    ('house_head', 'event.qr.manage'),
    ('vice_head', 'event.qr.manage'),
    ('liturgy_lead', 'event.qr.manage'),
    ('member', 'leave.request'),
    ('house_head', 'leave.review'),
    ('vice_head', 'leave.review'),
    ('house_head', 'poll.manage'),
    ('vice_head', 'poll.manage'),
    ('liturgy_lead', 'poll.manage'),
    ('member', 'poll.vote'),
    ('house_head', 'liturgy.manage'),
    ('vice_head', 'liturgy.manage'),
    ('liturgy_lead', 'liturgy.manage'),
    ('house_head', 'finance.summary.read'),
    ('vice_head', 'finance.summary.read'),
    ('treasurer', 'finance.summary.read'),
    ('member', 'finance.summary.read'),
    ('house_head', 'finance.ledger.read'),
    ('vice_head', 'finance.ledger.read'),
    ('treasurer', 'finance.ledger.read'),
    ('house_head', 'finance.fund.manage'),
    ('treasurer', 'finance.fund.manage'),
    ('member', 'finance.expense.create'),
    ('house_head', 'finance.expense.read_all'),
    ('vice_head', 'finance.expense.read_all'),
    ('treasurer', 'finance.expense.read_all'),
    ('house_head', 'finance.expense.approve'),
    ('treasurer', 'finance.expense.approve'),
    ('vice_head', 'finance.expense.approve'),
    ('treasurer', 'finance.expense.pay'),
    ('house_head', 'finance.expense.reverse'),
    ('treasurer', 'finance.expense.reverse'),
    ('house_head', 'finance.contribution.plan.manage'),
    ('treasurer', 'finance.contribution.plan.manage'),
    ('treasurer', 'finance.contribution.record'),
    ('house_head', 'finance.contribution.waive'),
    ('house_head', 'finance.contribution.read_all'),
    ('vice_head', 'finance.contribution.read_all'),
    ('treasurer', 'finance.contribution.read_all'),
    ('treasurer', 'finance.period.close'),
    ('house_head', 'finance.period.confirm'),
    ('house_head', 'finance.period.reopen'),
    ('treasurer', 'finance.reconcile'),
    ('house_head', 'finance.report.export'),
    ('treasurer', 'finance.report.export'),
    ('house_head', 'finance.ledger.adjust'),
    ('house_head', 'finance.settings.write'),
    ('member', 'issue.create'),
    ('admin', 'issue.read'),
    ('house_head', 'issue.read'),
    ('vice_head', 'issue.read'),
    ('treasurer', 'issue.read'),
    ('liturgy_lead', 'issue.read'),
    ('kitchen_lead', 'issue.read'),
    ('media_lead', 'issue.read'),
    ('member', 'issue.read'),
    ('house_head', 'issue.triage'),
    ('vice_head', 'issue.triage'),
    ('house_head', 'issue.resolve'),
    ('vice_head', 'issue.resolve'),
    ('house_head', 'issue.cost.propose'),
    ('vice_head', 'issue.cost.propose'),
    ('house_head', 'vendor.manage'),
    ('vice_head', 'vendor.manage'),
    ('admin', 'announcement.read'),
    ('house_head', 'announcement.read'),
    ('vice_head', 'announcement.read'),
    ('treasurer', 'announcement.read'),
    ('liturgy_lead', 'announcement.read'),
    ('kitchen_lead', 'announcement.read'),
    ('media_lead', 'announcement.read'),
    ('member', 'announcement.read'),
    ('house_head', 'announcement.create'),
    ('vice_head', 'announcement.create'),
    ('treasurer', 'announcement.create'),
    ('liturgy_lead', 'announcement.create'),
    ('kitchen_lead', 'announcement.create'),
    ('house_head', 'announcement.pin'),
    ('vice_head', 'announcement.pin'),
    ('member', 'forum.post'),
    ('house_head', 'forum.moderate'),
    ('vice_head', 'forum.moderate'),
    ('member', 'prayer.post'),
    ('house_head', 'prayer.moderate'),
    ('vice_head', 'prayer.moderate'),
    ('house_head', 'prayer.reveal_author'),
    ('member', 'album.create'),
    ('house_head', 'album.moderate'),
    ('vice_head', 'album.moderate'),
    ('media_lead', 'album.moderate'),
    ('member', 'laundry.book'),
    ('admin', 'laundry.manage'),
    ('house_head', 'laundry.manage'),
    ('vice_head', 'laundry.manage'),
    ('member', 'meal.register'),
    ('house_head', 'meal.manage'),
    ('vice_head', 'meal.manage'),
    ('kitchen_lead', 'meal.manage'),
    ('house_head', 'policy.manage'),
    ('member', 'policy.acknowledge'),
    ('house_head', 'notification.send'),
    ('vice_head', 'notification.send'),
    ('treasurer', 'notification.send'),
    ('liturgy_lead', 'notification.send'),
    ('kitchen_lead', 'notification.send'),
    ('admin', 'storage.upload'),
    ('house_head', 'storage.upload'),
    ('vice_head', 'storage.upload'),
    ('treasurer', 'storage.upload'),
    ('liturgy_lead', 'storage.upload'),
    ('kitchen_lead', 'storage.upload'),
    ('media_lead', 'storage.upload'),
    ('member', 'storage.upload'),
    ('house_head', 'ai.use'),
    ('vice_head', 'ai.use'),
    ('treasurer', 'ai.use'),
    ('liturgy_lead', 'ai.use'),
    ('kitchen_lead', 'ai.use'),
    ('media_lead', 'ai.use'),
    ('member', 'ai.use'),
    ('house_head', 'ai.review'),
    ('vice_head', 'ai.review'),
    ('treasurer', 'ai.review'),
    ('admin', 'ai.manage'),
    ('house_head', 'ai.manage')
  ) AS x(role_code, permission_code)
  JOIN roles r ON r.code = x.role_code
ON CONFLICT DO NOTHING;
