// Nhãn tiếng Việt cho nhật ký hoạt động: khóa = "<PHƯƠNG THỨC> <route>", route là đường dẫn API với giá trị tham số
// thay bằng [tên] (vd. "POST /api/v1/events/[id]/cancel"). Dùng chung cho server (gắn nhãn khi trả về) và giao diện.

export const ACTIVITY_AREAS: Record<string, string> = {
  finance: "Thu chi & Quỹ",
  event: "Sự kiện & Điểm danh",
  duty: "Trực nhật",
  member: "Thành viên & Hồ sơ",
  account: "Tài khoản & Phân quyền",
  setting: "Cài đặt & Danh mục",
  academic: "Học tập",
  kitchen: "Bếp & Thực phẩm",
  liturgy: "Phụng vụ",
  community: "Cộng đồng",
  house: "Nhà & Hậu cần",
  ai: "Trợ lý AI",
  integration: "Zalo & Tác vụ",
  auth: "Đăng nhập & Bảo mật",
  other: "Khác",
};

const A = (area: string, entries: Record<string, string>): [string, string, string][] =>
  Object.entries(entries).map(([k, label]) => [k, area, label]);

const RULES: [string, string, string][] = [
  ...A("auth", {
    "POST /api/v1/auth/logout": "Đăng xuất",
    "POST /api/v1/auth/password": "Đổi mật khẩu",
    "POST /api/v1/auth/register": "Đăng ký tài khoản",
  }),
  ...A("finance", {
    "POST /api/v1/finance/claims": "Báo đã đóng quỹ",
    "POST /api/v1/finance/claims/[id]/cancel": "Hủy báo đã đóng",
    "POST /api/v1/finance/claims/[id]/decide": "Xác nhận / từ chối khoản báo đã đóng",
    "POST /api/v1/finance/contribution-plans": "Tạo khoản thu",
    "POST /api/v1/finance/contribution-plans/[id]/cancel": "Hủy khoản thu",
    "POST /api/v1/finance/contribution-plans/[id]/remind": "Nhắc đóng quỹ",
    "POST /api/v1/finance/contributions/[id]/adjust": "Điều chỉnh khoản phải đóng",
    "POST /api/v1/finance/contributions/[id]/waive": "Miễn khoản phải đóng",
    "POST /api/v1/finance/expenses": "Tạo phiếu chi",
    "PATCH /api/v1/finance/expenses/[id]": "Sửa phiếu chi",
    "POST /api/v1/finance/expenses/[id]/[action]": "Xử lý phiếu chi (gửi / duyệt / từ chối / chi)",
    "POST /api/v1/finance/payments": "Ghi nhận đã thu tiền",
    "POST /api/v1/finance/payments/[id]/void": "Hủy phiếu thu",
    "PUT /api/v1/finance/receiving-account": "Cập nhật tài khoản nhận tiền",
  }),
  ...A("event", {
    "POST /api/v1/events": "Tạo sự kiện",
    "PATCH /api/v1/events/[id]": "Sửa sự kiện",
    "DELETE /api/v1/events/[id]": "Xóa sự kiện",
    "POST /api/v1/events/[id]/cancel": "Hủy sự kiện",
    "POST /api/v1/events/[id]/rsvp": "Phản hồi tham dự sự kiện",
    "POST /api/v1/events/[id]/attendance": "Điểm danh hộ",
    "POST /api/v1/events/[id]/attendance/close": "Chốt điểm danh",
    "POST /api/v1/events/[id]/qr": "Mở phiên điểm danh QR",
    "DELETE /api/v1/events/[id]/qr": "Đóng phiên điểm danh QR",
    "POST /api/v1/events/checkin": "Tự điểm danh",
    "POST /api/v1/polls": "Tạo biểu quyết",
    "POST /api/v1/polls/[id]/vote": "Bỏ phiếu biểu quyết",
    "POST /api/v1/polls/[id]/close": "Đóng biểu quyết",
    "DELETE /api/v1/polls/[id]": "Xóa biểu quyết",
  }),
  ...A("duty", {
    "POST /api/v1/duty/weeks": "Lập lịch trực tuần",
    "DELETE /api/v1/duty/weeks/[id]": "Xóa lịch trực tuần",
    "POST /api/v1/duty/weeks/[id]/review": "Nhận xét / chấm điểm trực tuần",
    "POST /api/v1/duty/weeks/[id]/remind": "Nhắc lịch trực tuần",
    "POST /api/v1/duty/weeks/[id]/zalo": "Gửi lịch trực vào Zalo",
    "POST /api/v1/duty/rosters": "Tạo bảng phân công trực",
    "POST /api/v1/duty/rosters/[id]/publish": "Công bố bảng phân công",
    "DELETE /api/v1/duty/rosters/[id]": "Xóa bảng phân công",
    "POST /api/v1/duty/assignments": "Thêm ca trực",
    "PATCH /api/v1/duty/assignments/[id]": "Sửa ca trực",
    "DELETE /api/v1/duty/assignments/[id]": "Xóa ca trực",
    "POST /api/v1/duty/assignments/[id]/checkin": "Check-in ca trực",
    "POST /api/v1/duty/assignments/[id]/review": "Đánh giá ca trực",
    "POST /api/v1/duty/swaps": "Xin đổi ca trực",
    "POST /api/v1/duty/swaps/[id]/respond": "Phản hồi đổi ca",
    "POST /api/v1/duty/swaps/[id]/decide": "Duyệt đổi ca",
    "POST /api/v1/duty/swaps/[id]/cancel": "Hủy đổi ca",
  }),
  ...A("member", {
    "POST /api/v1/members": "Thêm thành viên",
    "PATCH /api/v1/members/[id]": "Sửa hồ sơ thành viên",
    "POST /api/v1/members/[id]/status": "Đổi trạng thái thành viên",
    "POST /api/v1/members/[id]/national-id": "Xem CCCD thành viên",
    "PUT /api/v1/members/[id]/payment-account": "Cập nhật tài khoản ngân hàng thành viên",
    "DELETE /api/v1/members/[id]/payment-account": "Xóa tài khoản ngân hàng thành viên",
    "POST /api/v1/applications/[id]/approve": "Duyệt đơn vào lưu xá",
    "POST /api/v1/applications/[id]/reject": "Từ chối đơn vào lưu xá",
  }),
  ...A("account", {
    "POST /api/v1/accounts": "Cấp tài khoản đăng nhập",
    "PATCH /api/v1/accounts/[userId]": "Khóa / mở khóa tài khoản",
    "POST /api/v1/accounts/[userId]/password-reset": "Đặt lại mật khẩu",
    "POST /api/v1/accounts/[userId]/roles": "Đổi vai trò tài khoản",
    "POST /api/v1/members/[id]/account": "Cấp tài khoản cho thành viên",
    "POST /api/v1/members/[id]/password-reset": "Đặt lại mật khẩu thành viên",
    "POST /api/v1/members/[id]/roles": "Gán vai trò thành viên",
    "POST /api/v1/rbac/roles": "Tạo vai trò",
    "PATCH /api/v1/rbac/roles/[code]": "Sửa vai trò / phân quyền",
    "DELETE /api/v1/rbac/roles/[code]": "Xóa vai trò",
  }),
  ...A("setting", {
    "PATCH /api/v1/settings": "Lưu cấu hình hệ thống",
    "PUT /api/v1/settings/[key]": "Sửa một cấu hình",
    "POST /api/v1/settings/reset": "Khôi phục cấu hình mặc định",
    "POST /api/v1/settings/[key]/reset": "Khôi phục một cấu hình mặc định",
    "POST /api/v1/categories": "Tạo danh mục",
    "PATCH /api/v1/categories/[id]": "Sửa danh mục",
    "DELETE /api/v1/categories/[id]": "Xóa danh mục",
    "PUT /api/v1/ui/modules": "Bật / tắt phân hệ",
    "POST /api/v1/reminders": "Tạo lịch nhắc lặp",
    "PATCH /api/v1/reminders/[id]": "Sửa lịch nhắc lặp",
    "DELETE /api/v1/reminders/[id]": "Xóa lịch nhắc lặp",
    "POST /api/v1/house-rules": "Thêm mục luật nhà",
    "PATCH /api/v1/house-rules/[id]": "Sửa mục luật nhà",
    "DELETE /api/v1/house-rules/[id]": "Xóa mục luật nhà",
    "POST /api/v1/house-rules/reorder": "Sắp xếp luật nhà",
  }),
  ...A("academic", {
    "POST /api/v1/academic/records": "Nhập bảng điểm",
    "PATCH /api/v1/academic/records/[id]": "Sửa bảng điểm",
    "DELETE /api/v1/academic/records/[id]": "Xóa bảng điểm",
    "POST /api/v1/academic/records/[id]/[action]": "Xử lý bảng điểm (gửi / duyệt / trả lại)",
    "POST /api/v1/academic/config/years": "Tạo năm học",
    "PATCH /api/v1/academic/config/years/[id]": "Sửa năm học",
    "DELETE /api/v1/academic/config/years/[id]": "Xóa năm học",
    "POST /api/v1/academic/config/semesters": "Tạo học kỳ",
    "PATCH /api/v1/academic/config/semesters/[id]": "Sửa học kỳ",
    "DELETE /api/v1/academic/config/semesters/[id]": "Xóa học kỳ",
    "POST /api/v1/academic/config/universities": "Thêm trường",
    "PATCH /api/v1/academic/config/universities/[id]": "Sửa trường",
    "DELETE /api/v1/academic/config/universities/[id]": "Xóa trường",
    "POST /api/v1/academic/config/board-terms": "Thêm nhiệm kỳ ban điều hành",
    "PATCH /api/v1/academic/config/board-terms/[id]": "Sửa nhiệm kỳ ban điều hành",
    "DELETE /api/v1/academic/config/board-terms/[id]": "Xóa nhiệm kỳ ban điều hành",
  }),
  ...A("kitchen", {
    "PUT /api/v1/meals/registrations": "Đăng ký suất ăn",
    "POST /api/v1/meals/registrations/bulk": "Đăng ký suất ăn hàng loạt",
    "PUT /api/v1/meals/menus": "Cập nhật thực đơn",
    "PUT /api/v1/meals/menus/[id]/feedback": "Đánh giá bữa ăn",
    "DELETE /api/v1/meals/menus/[id]/feedback": "Xóa đánh giá bữa ăn",
    "PATCH /api/v1/meals/settings": "Sửa cấu hình bữa ăn",
    "POST /api/v1/meals/surveys": "Tạo khảo sát bữa ăn",
    "PATCH /api/v1/meals/surveys/[id]": "Sửa khảo sát bữa ăn",
    "DELETE /api/v1/meals/surveys/[id]": "Xóa khảo sát bữa ăn",
    "POST /api/v1/meals/surveys/[id]/options": "Thêm lựa chọn khảo sát",
    "PUT /api/v1/meals/surveys/[id]/votes": "Bình chọn khảo sát bữa ăn",
    "POST /api/v1/pantry/items": "Thêm vật dụng kho",
    "PATCH /api/v1/pantry/items/[id]": "Sửa vật dụng kho",
    "DELETE /api/v1/pantry/items/[id]": "Xóa vật dụng kho",
    "POST /api/v1/pantry/restock-requests": "Yêu cầu bổ sung kho",
    "PATCH /api/v1/pantry/restock-requests/[id]": "Xử lý yêu cầu bổ sung kho",
    "POST /api/v1/pantry/shopping": "Thêm mục đi chợ",
    "PATCH /api/v1/pantry/shopping/[id]": "Sửa mục đi chợ",
    "DELETE /api/v1/pantry/shopping/[id]": "Xóa mục đi chợ",
  }),
  ...A("liturgy", {
    "POST /api/v1/liturgy/assignments": "Phân công phụng vụ",
    "PATCH /api/v1/liturgy/assignments/[id]": "Sửa phân công phụng vụ",
    "DELETE /api/v1/liturgy/assignments/[id]": "Xóa phân công phụng vụ",
    "PUT /api/v1/liturgy/calendar/[date]/note": "Ghi chú lịch phụng vụ",
    "POST /api/v1/liturgy/checkins": "Check-in đi lễ",
    "POST /api/v1/liturgy/checkins/[id]/review": "Duyệt check-in đi lễ",
    "DELETE /api/v1/liturgy/checkins/[id]": "Xóa check-in đi lễ",
    "POST /api/v1/liturgy/documents": "Thêm tài liệu phụng vụ",
    "PATCH /api/v1/liturgy/documents/[id]": "Sửa tài liệu phụng vụ",
    "DELETE /api/v1/liturgy/documents/[id]": "Xóa tài liệu phụng vụ",
    "POST /api/v1/liturgy/lectionary": "Nạp bài đọc",
    "POST /api/v1/liturgy/reflections": "Viết suy niệm",
    "DELETE /api/v1/liturgy/reflections/[id]": "Xóa suy niệm",
    "POST /api/v1/liturgy/sessions": "Mở buổi đi lễ",
    "DELETE /api/v1/liturgy/sessions/[id]": "Xóa buổi đi lễ",
    "POST /api/v1/liturgy/special-days": "Thêm ngày lễ đặc biệt",
    "PUT /api/v1/liturgy/special-days/[id]": "Sửa ngày lễ đặc biệt",
    "DELETE /api/v1/liturgy/special-days/[id]": "Xóa ngày lễ đặc biệt",
    "POST /api/v1/prayers": "Gửi ý cầu nguyện",
    "POST /api/v1/prayers/[id]/pray": "Cầu nguyện cho một ý",
    "POST /api/v1/prayers/[id]/report": "Báo cáo ý cầu nguyện",
    "POST /api/v1/prayers/[id]/reports": "Xử lý báo cáo ý cầu nguyện",
    "POST /api/v1/prayers/[id]/reveal": "Xem tác giả ý cầu nguyện ẩn danh",
    "POST /api/v1/prayers/[id]/status": "Đổi trạng thái ý cầu nguyện",
    "POST /api/v1/prayers/[id]/visibility": "Đổi chế độ hiển thị ý cầu nguyện",
  }),
  ...A("community", {
    "POST /api/v1/announcements": "Đăng thông báo",
    "DELETE /api/v1/announcements/[id]": "Xóa thông báo",
    "POST /api/v1/announcements/[id]/pin": "Ghim thông báo",
    "POST /api/v1/announcements/[id]/read": "Đánh dấu đã đọc thông báo",
    "POST /api/v1/announcements/[id]/rsvp": "Phản hồi thông báo",
    "POST /api/v1/announcements/read-all": "Đọc tất cả thông báo",
    "POST /api/v1/notifications/[id]/read": "Đánh dấu đã đọc",
    "POST /api/v1/notifications/read-all": "Đọc tất cả thông báo",
    "POST /api/v1/forum/posts": "Đăng bài diễn đàn",
    "PATCH /api/v1/forum/posts/[id]": "Sửa bài diễn đàn",
    "DELETE /api/v1/forum/posts/[id]": "Xóa bài diễn đàn",
    "POST /api/v1/forum/posts/[id]/comments": "Bình luận diễn đàn",
    "POST /api/v1/forum/posts/[id]/like": "Thích bài diễn đàn",
    "POST /api/v1/forum/posts/[id]/report": "Báo cáo bài diễn đàn",
    "POST /api/v1/forum/posts/[id]/reports": "Xử lý báo cáo bài diễn đàn",
    "PATCH /api/v1/forum/comments/[id]": "Sửa bình luận",
    "DELETE /api/v1/forum/comments/[id]": "Xóa bình luận",
    "POST /api/v1/forum/comments/[id]/report": "Báo cáo bình luận",
    "POST /api/v1/forum/comments/[id]/reports": "Xử lý báo cáo bình luận",
    "POST /api/v1/moments": "Tạo album",
    "PATCH /api/v1/moments/[id]": "Sửa album",
    "DELETE /api/v1/moments/[id]": "Xóa album",
    "POST /api/v1/moments/[id]/photos": "Thêm ảnh vào album",
    "POST /api/v1/moments/[id]/like": "Thích album",
    "DELETE /api/v1/moments/[id]/like": "Bỏ thích album",
    "POST /api/v1/moments/[id]/tag": "Gắn thẻ thành viên trong album",
    "PATCH /api/v1/moments/photos/[photoId]": "Sửa ảnh",
    "DELETE /api/v1/moments/photos/[photoId]": "Xóa ảnh",
    "POST /api/v1/moments/photos/[photoId]/like": "Thích ảnh",
    "DELETE /api/v1/moments/photos/[photoId]/like": "Bỏ thích ảnh",
    "POST /api/v1/files": "Tải tệp lên",
  }),
  ...A("house", {
    "POST /api/v1/house/floors": "Thêm tầng",
    "PATCH /api/v1/house/floors/[level]": "Sửa tầng",
    "DELETE /api/v1/house/floors/[level]": "Xóa tầng",
    "POST /api/v1/house/rooms": "Thêm phòng",
    "PATCH /api/v1/house/rooms/[code]": "Sửa phòng",
    "DELETE /api/v1/house/rooms/[code]": "Xóa phòng",
    "POST /api/v1/house/assignments": "Xếp phòng cho thành viên",
    "DELETE /api/v1/house/assignments/[memberId]": "Gỡ thành viên khỏi phòng",
    "POST /api/v1/issues": "Báo sự cố / hỏng hóc",
    "PATCH /api/v1/issues/[id]": "Cập nhật sự cố",
    "POST /api/v1/issues/[id]/assign": "Giao xử lý sự cố",
    "POST /api/v1/issues/[id]/verify": "Nghiệm thu sự cố",
    "POST /api/v1/issues/[id]/photos": "Thêm ảnh sự cố",
    "POST /api/v1/issues/[id]/costs": "Thêm chi phí sửa chữa",
    "DELETE /api/v1/issues/[id]/costs/[costId]": "Xóa chi phí sửa chữa",
  }),
  ...A("ai", {
    "POST /api/v1/ai/run": "Chạy trợ lý AI",
    "PUT /api/v1/ai/consent": "Đồng ý / rút đồng ý dùng AI",
    "PUT /api/v1/ai/budget": "Sửa hạn mức AI",
    "PATCH /api/v1/ai/tasks/[code]": "Bật / tắt tác vụ AI",
    "POST /api/v1/ai/suggestions/[id]/decision": "Duyệt gợi ý AI",
  }),
  ...A("integration", {
    "POST /api/v1/integrations/zalo/send": "Gửi tin vào nhóm Zalo",
    "POST /api/v1/integrations/zalo/test": "Gửi tin thử Zalo",
    "POST /api/v1/integrations/cron/run": "Chạy tác vụ hằng ngày thủ công",
  }),
];

const BY_KEY = new Map(RULES.map(([k, area, label]) => [k, { area, label }]));

const SEGMENT_AREA: Record<string, string> = {
  finance: "finance", events: "event", polls: "event", duty: "duty", members: "member", applications: "member", accounts: "account",
  rbac: "account", settings: "setting", categories: "setting", reminders: "setting", "house-rules": "setting", academic: "academic",
  meals: "kitchen", pantry: "kitchen", liturgy: "liturgy", prayers: "liturgy", announcements: "community", notifications: "community",
  forum: "community", moments: "community", files: "community", house: "house", issues: "house", ai: "ai", integrations: "integration", auth: "auth",
};

export interface ActivityLabel {
  area: string;
  areaLabel: string;
  label: string;
}

/** Nhãn dễ đọc cho một thao tác; route chưa có trong bảng thì dùng "<PHƯƠNG THỨC> <route>" và suy phân hệ từ đường dẫn. */
export function activityLabel(method: string, route: string): ActivityLabel {
  const hit = BY_KEY.get(`${method} ${route}`);
  if (hit) return { ...hit, areaLabel: ACTIVITY_AREAS[hit.area] };
  const seg = route.split("/")[3] ?? "";
  const area = SEGMENT_AREA[seg] ?? "other";
  return { area, areaLabel: ACTIVITY_AREAS[area], label: `${method} ${route.replace(/^\/api\/v1/, "")}` };
}

/** Các route (khóa "<PHƯƠNG THỨC> <route>") thuộc một phân hệ — để lọc phía DB. */
export function routesOfArea(area: string): string[] {
  return RULES.filter(([, a]) => a === area).map(([k]) => k);
}

/** Khóa "<PHƯƠNG THỨC> <route>" có nhãn chứa chuỗi tìm kiếm (không phân biệt hoa thường) — để lọc phía DB. */
export function routesMatching(q: string): string[] {
  const s = q.trim().toLowerCase();
  if (!s) return [];
  return RULES.filter(([k, , label]) => label.toLowerCase().includes(s) || k.toLowerCase().includes(s)).map(([k]) => k);
}

/** Tên dễ đọc của bảng dữ liệu trong audit_logs (bảng chưa có trong danh sách hiển thị đúng tên bảng). */
export const ENTITY_LABEL: Record<string, string> = {
  users: "Tài khoản",
  user_roles: "Vai trò của tài khoản",
  role_delegations: "Ủy quyền vai trò",
  roles: "Vai trò",
  role_permissions: "Quyền của vai trò",
  settings: "Cấu hình hệ thống",
  categories: "Danh mục",
  members: "Thành viên",
  member_private_details: "Thông tin riêng của thành viên",
  catholic_profiles: "Hồ sơ Công giáo",
  student_profiles: "Hồ sơ sinh viên",
  member_applications: "Đơn xin vào lưu xá",
  board_terms: "Nhiệm kỳ ban điều hành",
  member_positions: "Chức vụ",
  academic_years: "Năm học",
  semesters: "Học kỳ",
  floors: "Tầng",
  rooms: "Phòng",
  room_assignments: "Xếp phòng",
  funds: "Quỹ",
  financial_periods: "Kỳ tài chính",
  expense_vouchers: "Phiếu chi",
  expense_approvals: "Duyệt phiếu chi",
  contribution_plans: "Khoản thu",
  contributions: "Khoản phải đóng",
  contribution_payments: "Phiếu thu",
  contribution_claims: "Báo đã đóng",
  contribution_payment_allocations: "Phân bổ phiếu thu",
  ledger_entries: "Sổ quỹ",
  duty_rosters: "Bảng phân công trực",
  duty_assignments: "Ca trực",
  duty_assignment_members: "Người trực",
  duty_reviews: "Đánh giá trực",
  duty_weeks: "Lịch trực tuần",
  house_rule_sections: "Luật nhà",
  recurring_reminders: "Lịch nhắc lặp",
  events: "Sự kiện",
  polls: "Biểu quyết",
  announcements: "Thông báo",
};
